#!/usr/bin/env bash
set -eu

ROOT_DIR=`dirname "$(realpath "$0")"`

which nix 2> /dev/null > /dev/null && {
    TMPFILE=`mktemp`
    cat << EOF > "$TMPFILE"
with import <nixpkgs> {};
python3.withPackages (pkgs: with pkgs; [
    numpy
])
EOF

    out="$(nix-build "$TMPFILE" --no-out-link)"
    PATH="$out/bin:$PATH"
    python3 "$ROOT_DIR/matcrypt.py" "$@"
}

which python3 2> /dev/null > /dev/null || {
    echo "Python 3 não instalado, não tenho muito o que fazer ¯\_(ツ)_/¯"
    exit 1
}

python3 -c 'import numpy as np' 2> /dev/null > /dev/null || {
    echo "Sem numpy instalado"
    exit 1
}

python3 "$ROOT_DIR/matcrypt.py" "$@"

